dist: xenial
language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "nightly"
install:
  - pip install codecov
  - pip install coverage
  - pip install pillow
script:
  - python main.py < tests/test-main.txt
  - coverage run tests/test_gen_ascii.py
after_success:
  - codecov
