dist: xenial
language: python
python:
 - "3.6"
 - "3.7"
 - "nightly"
notifications:
  email: false
install:
  - pip install codecov
  - pip install coverage
  - pip install pillow
script:
  - coverage run main.py < tests/test-main.txt
  - coverage run test_gen_ascii.py
after_success:
  - codecov
